/**
 * End-to-end suite for the `ok` examples (`kind: "ok"` in `examples/index.json`).
 *
 * For every committed clean program, this drives the **real** lexer → parser →
 * interpreter pipeline via the public `interpret()` facade and asserts that:
 *   • it runs successfully — `ok === true`, no diagnostics of any phase; and
 *   • its captured `print`/`println` output is **byte-exact** equal to the
 *     committed `examples/<name>.out` golden.
 *
 * The suite is fully data-driven: it iterates the manifest and reads each
 * program + golden from disk. It hard-codes NO per-example expectation, so adding
 * a new `ok` example (with its generated golden) extends coverage automatically.
 */

import { describe, expect, it } from "vitest";

import { entriesOfKind, readOutGolden, runExample } from "./harness";

const okExamples = entriesOfKind("ok");

describe("examples — ok programs run clean and match their golden stdout", () => {
  it("has at least one ok example to exercise", () => {
    expect(okExamples.length).toBeGreaterThan(0);
  });

  it.each(okExamples.map((entry) => entry.name))(
    "runs %s cleanly and reproduces its golden stdout byte-for-byte",
    (name) => {
      const { outcome, stdout } = runExample(name);

      // A clean example must run without a single diagnostic of any phase.
      expect(outcome.diagnostics).toEqual([]);
      expect(outcome.ok).toBe(true);

      // The golden was generated by really running this program; a real run must
      // still reproduce it exactly (color-free, deterministic).
      expect(stdout).toBe(readOutGolden(name));
    },
  );
});
