/**
 * Shared harness for the end-to-end / error example suites.
 *
 * The integration layer proves the WHOLE composes: every program committed under
 * `examples/` is run through the **real** interpreter — the same public surface a
 * library consumer or the shipped CLI drives — and asserted against the goldens
 * that the `examples` task generated by actually running those programs. Nothing
 * here re-derives the pipeline or mocks a stage; the point is fidelity to real
 * behavior.
 *
 * Everything is **data-driven from `examples/index.json`**: the suites iterate the
 * manifest and never hard-code per-example expectations. This file owns the
 * shared plumbing both suites (`tests/integration/**`, `tests/errors/**`) build
 * on — manifest loading, golden reading, a deterministic color-free capture of
 * `print`/`println`, the CLI-faithful diagnostic reconstruction, and a true
 * child-process runner for the shipped `bin/klein.mjs`.
 *
 * It has no `*.test.ts` suffix, so Vitest does not collect it as a suite (mirroring
 * `tests/stdlib/harness.ts` and `tests/parser/helpers.ts`). Assertions in the
 * suites key off structured `ErrorCode`s and byte-exact goldens, never off
 * human-readable diagnostic message text (per the project quality bar).
 */

import { spawnSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { formatDiagnostic } from "@core";

import {
  interpret,
  type Diagnostic,
  type InterpretOutcome,
} from "../../src/index";

/**
 * The project root, resolved relative to THIS file (not the importer): this
 * harness lives at `tests/integration/harness.ts`, so `../../` is the package
 * root regardless of whether the importing suite sits in `tests/integration/` or
 * `tests/errors/`. `import.meta.url` always refers to this module's own URL.
 */
export const projectRoot = fileURLToPath(new URL("../../", import.meta.url));

/** Absolute path to a file under the project root. */
function fromRoot(...segments: readonly string[]): string {
  return fileURLToPath(
    new URL(segments.join("/"), new URL("../../", import.meta.url)),
  );
}

/**
 * One entry of the shared example manifest (`examples/index.json`, defined in the
 * subtree hub §3). `expectedCodes` is present iff `kind === "error"` and lists the
 * `ErrorCode` string values the run must emit, in source order.
 */
export interface ManifestEntry {
  readonly name: string;
  readonly kind: "ok" | "error";
  readonly expectedCodes?: readonly string[];
}

/** Load and parse `examples/index.json` once per importing suite. */
export function loadManifest(): readonly ManifestEntry[] {
  const raw = readFileSync(fromRoot("examples", "index.json"), "utf8");
  const parsed: unknown = JSON.parse(raw);
  if (!Array.isArray(parsed)) {
    throw new Error(
      "examples/index.json must be a JSON array of manifest entries",
    );
  }
  return parsed as readonly ManifestEntry[];
}

/** Manifest entries of a given kind. */
export function entriesOfKind(kind: "ok" | "error"): readonly ManifestEntry[] {
  return loadManifest().filter((entry) => entry.kind === kind);
}

/**
 * The logical source name a diagnostic is anchored to. It MUST match the path the
 * CLI is invoked with (`node bin/klein.mjs examples/<name>.kl`), because that path
 * is what the `examples` task baked into the `.diag` goldens' `--> …:line:col`
 * locations and stack frames.
 */
export function sourceNameFor(name: string): string {
  return `examples/${name}.kl`;
}

/** Read a committed example program's source. */
export function readSource(name: string): string {
  return readFileSync(fromRoot("examples", `${name}.kl`), "utf8");
}

/** Read the golden stdout (`.out`) for an example. May be empty. */
export function readOutGolden(name: string): string {
  return readFileSync(fromRoot("examples", `${name}.out`), "utf8");
}

/** Read the golden rendered diagnostics (`.diag`) for an error example. */
export function readDiagGolden(name: string): string {
  return readFileSync(fromRoot("examples", `${name}.diag`), "utf8");
}

/** The outcome of running one example in-process, plus its captured stdout. */
export interface ExampleRun {
  readonly outcome: InterpretOutcome;
  /** Everything the program wrote via `print`/`println`, concatenated. */
  readonly stdout: string;
}

/**
 * Run one committed example through the real `interpret()` facade, capturing its
 * `print`/`println` output into a deterministic, color-free string sink. The
 * facade emits no color, so the captured bytes are directly comparable to the
 * `.out` golden.
 */
export function runExample(name: string): ExampleRun {
  const chunks: string[] = [];
  const outcome = interpret(readSource(name), {
    sourceName: sourceNameFor(name),
    write: (text) => {
      chunks.push(text);
    },
  });
  return { outcome, stdout: chunks.join("") };
}

/**
 * Reconstruct the exact stderr text the shipped CLI renders for a set of
 * diagnostics: each diagnostic rendered through the shared `@core`
 * `formatDiagnostic` (color disabled) and terminated with a newline, in source
 * order. This mirrors `runSource` in `src/cli/cli.ts` byte-for-byte, so the result
 * is directly comparable to a committed `.diag` golden.
 */
export function renderDiagnostics(
  diagnostics: readonly Diagnostic[],
  source: string,
): string {
  return diagnostics
    .map(
      (diagnostic) =>
        `${formatDiagnostic(diagnostic, source, { color: false })}\n`,
    )
    .join("");
}

/** The result of a true child-process run of `bin/klein.mjs`. */
export interface ProcessRun {
  readonly status: number | null;
  readonly stdout: string;
  readonly stderr: string;
}

/**
 * Spawn the shipped executable end-to-end: `node bin/klein.mjs <relFile>` from the
 * project root, with `NO_COLOR` set for stable, color-free output. This exercises
 * the REAL `bin` → `tsx` → `main` path — not the in-process facade — proving the
 * package's advertised entry actually runs. `spawnSync` is used so a non-zero exit
 * is returned rather than thrown; callers assert on `status` directly.
 */
export function spawnKlein(relFile: string): ProcessRun {
  // Inherit the parent env but force a clean, color-free run: set NO_COLOR and
  // strip FORCE_COLOR. Leaving FORCE_COLOR set would both override NO_COLOR and
  // make Node print an "'NO_COLOR' is ignored…" warning to the child's stderr,
  // which is exactly the stream the diagnostic goldens assert on.
  const env: NodeJS.ProcessEnv = { ...process.env, NO_COLOR: "1" };
  delete env["FORCE_COLOR"];

  const result = spawnSync(process.execPath, ["bin/klein.mjs", relFile], {
    cwd: projectRoot,
    encoding: "utf8",
    env,
  });
  if (result.error) {
    throw result.error;
  }
  return {
    status: result.status,
    stdout: result.stdout,
    stderr: result.stderr,
  };
}
